<div class="row-fluid">
	<div class="span2">
		<a href="/admin/book"><img src="/img/book.png"></a><br>
		<a href="/admin/book">Добавить книгу</a>
	</div>	
	<div class="span2">
		<a href="/admin/category"><img src="/img/category.png"></a><br>
		<a href="/admin/category">Добавить категорию</a>
	</div>
	<div class="span2">
		<a href="/admin/author"><img src="/img/author.png"></a><br>
		<a href="/admin/author">Добавить автора</a>
	</div>	
</div>
