<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$error=$this->formElementErrors($form->get('identity'));
?>


<?if(!empty($error)){ ?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php echo $error; ?>
    </div>
<?}?>
<div class="container">
        <?php echo $this->form()->openTag($form) ?>
            

            <h2 class="form-signin-heading">Админ-панель</h2>
            <div class="control-group ">
                <?php echo $this->formInput($form->get('identity')) ?>
            </div>
            <div class="control-group">
                <?php echo $this->formInput($form->get('credential')) ?>
            </div>
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
            <?php echo $this->formButton($form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
</div>




