<? $errors[]=$this->formElementErrors($form->get('name')); 

?>
<?if(isset($success)){?>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Успешно Добавлено!</strong>
  </div>
<?}?>
<div class="succ_mess"></div>
<?if(isset($errors)){ 
	foreach ($errors as  $error) {?>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><?=$error?></strong>
    </div>
<?}}?>
<?if(isset($error)&&$error!=""){ ?>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><?=$error?></strong>
    </div>
<?}?>
<?if(isset($cat_delete)){?>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Успешно Удалена!</strong>
  </div>
<?}?>
  <div>
    <div class="span2">
    	Рубрика
    </div>
    <div class="span10">
      <?php  
       $form->setAttribute('class', 'form');
       echo $this->form()->openTag($form); ?>
       <div class="input-append">
       <?php echo $this->formHidden($form->get('category_id'));
       echo $this->formInput($form->get('name'));
       echo $this->formSubmit($form->get('btn_addcat'));
       ?>
       </div> 
       <?
       echo $this->form()->closeTag();
       ?>
    <div class="table_href">
  		<table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Название</th>
              <th>Просмотр</th>
              <th>Редактирование</th>
              <th>Удаление</th>
            </tr>
          </thead>
          <tbody>
          	<? if(!empty($categories)) {foreach ($categories as $cat){?>
              <tr>
                <td><?=$cat['category_id']?></td>
                <td><?=$cat['name']?></td>
                <td><a href="/cat?id=<?=$cat['category_id']?>"><i class="icon-eye-open" title="Просмотр"></i></a></td>
                <td><a href="#myModal"  data-toggle="modal"><i data-id="<?=$cat['category_id']?>" class="icon-edit" title="Редактировать"></i></a></td>
                <td><a href="/admin/deletecategory?id=<?=$cat['category_id']?>"><i class="icon-remove" title="Удалить"></i></a></td>
              </tr>
            <?}}?>
          </tbody>
      </table>    	
    </div>
  </div>
</div>
 
<script type="text/javascript">
$(document).ready(function() { 
$( ".span10 .table_href" ).on( "click", ".icon-edit", function() {
    idcat=$(this).data( "id");
   $("#myModal").load("/admin/editcategory?category_id="+idcat);
});

$( "#myModal" ).on( "click", ".btn_editcat", function() {
  id=$( "#myModal input.span4" ).val();
  name=$( "#myModal input.span3" ).val();
  $.ajax({
      type:"POST",
      url: '/admin/editcategory',
      data:"category_id="+id+"&name="+name,
      success: function(response) {
        var data = response ;
              $('#myModal').modal('hide');
              text='<div class="alert alert-success edit_success"><button type="button" class="close" data-dismiss="alert">&times;</button><strong>Успешно изменено!</strong></div>';
              $(".succ_mess").empty();
              $(".err_mess").empty();
              $(".succ_mess").append(text);
              $(".table_href").load("/admin/category .table");
      }
  });

});
});
</script>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>