<? $error=$this->formElementErrors($form->get('name')); ?>
<?if(isset($error)&&$error!=""){ ?>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><?=$error?></strong>
    </div>
<?}?>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Изменить рубрику</h3>
  </div>
  <div class="modal-body">
    <div class="err_mess"></div>
	<?php $form->setAttribute('class', 'form form_edit');
	      echo $this->form()->openTag($form); ?>
      <div class="input-append">
        <? echo $this->formInput($form->get('name')); ?>
      	<? echo $this->formInput($form->get('category_id')); ?>
        <!--input class="span3" id="name_catedit" data-id="" placeholder="Введите название рубрики" name="name" type="text"-->
      </div>  
       <? echo $this->form()->closeTag(); ?>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Закрыть</button>
    <button class="btn btn-primary btn_editcat">Сохранить</button>
  </div>
