        <div class="what-we-do container">
            <div class="row">
                <div class="portfolio-navigator span12">
                    <h4 class="filter-portfolio">
                       Рубрики
                    </h4>
                </div>
            </div>
            <div class="row">
                <? if(isset($categories)) { foreach ($categories as  $cat) {?>
                    <div class="service span3">
                        <div class="icon-awesome">
                            <a href="<?=$cat['href']?>">
                                <i class="icon-folder-open"></i>
                            </a>
                        </div>
                        <a href="<?=$cat['href']?>">
                            <h4><?=$cat['name']?></h4>
                        
                    </div>
                <?}}?>
            </div>
        </div>
        <!-- Call To Action -->
        <div class="call-to-action container">
        </div>